### ISSUE TITLE
Using `-c` prevents CNAME configuration from being restored

### ISSUE THREAD

**Issue by bdruth** [chamilad/pihole-restore#4]
Not sure what's going on, but on a fresh pihole install, using the `-c` option will result in seemingly everything being restored *except* CNAME configurations. Lemme know if you need more info.

Thanks for this utility!

**Comment by bdruth** [comment]
This seems to _only_ happen on a fresh install, for some reason - if I run `pihole_restore` after that, without the '-c', the CNAMEs are restored, and after _that_, running it again with `-c` works as expected (table cleared, CNAMEs restored).

**Comment by chamilad** [comment]
Hey @bdruth , sorry I've been away from this for a while. Let me check and fix this, but it'll take a couple of weeks because of some life events. 

edit: running on a single DNS server these days so I haven't been able to test this on new versions. Early uneducated guess is an API change, but let's see.

**Comment by bdruth** [comment]
No rush! Thanks for looking into it!!

**Comment by chamilad** [comment]
reproduced
